#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jdom
Version  : 1.1
Release  : 1
URL      : https://repo1.maven.org/maven2/org/jdom/jdom/1.1/jdom-1.1.jar
Source0  : https://repo1.maven.org/maven2/org/jdom/jdom/1.1/jdom-1.1.jar
Source1  : https://repo1.maven.org/maven2/org/jdom/jdom/1.1/jdom-1.1.pom
Source2  : https://repo1.maven.org/maven2/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar
Source3  : https://repo1.maven.org/maven2/org/jdom/jdom2/2.0.6/jdom2-2.0.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Saxpath
Requires: mvn-jdom-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jdom package.
Group: Data

%description data
data components for the mvn-jdom package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom/1.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom2/2.0.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom2/2.0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom2/2.0.6
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/jdom/jdom2/2.0.6


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jdom/jdom/1.1/jdom-1.1.jar
/usr/share/java/.m2/repository/org/jdom/jdom/1.1/jdom-1.1.pom
/usr/share/java/.m2/repository/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar
/usr/share/java/.m2/repository/org/jdom/jdom2/2.0.6/jdom2-2.0.6.pom
